#!/usr/bin/env python3
"""Generate dependency-free TypeScript modules from starter YAML and JSON catalogs."""
from __future__ import annotations

import json
from pathlib import Path
import yaml
from template_normalization import normalize_template_input

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "starter-pack" / "templates"
MANIFEST_PATH = ROOT / "starter-pack" / "manifest.yaml"
CATALOG_PATH = ROOT / "schemas" / "webmcp-tool-catalog.json"
OUT_TEMPLATES = ROOT / "src" / "generated" / "starterTemplates.ts"
OUT_CATALOG = ROOT / "src" / "generated" / "webmcpCatalog.ts"


def dump(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def main() -> None:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text())
    templates = {}
    for path in sorted(TEMPLATE_DIR.glob("*.yaml")):
        template = normalize_template_input(yaml.safe_load(path.read_text()))
        if not isinstance(template, dict):
            raise SystemExit(f"{path.name}: template root must be a mapping")
        templates[template["id"]] = template

    expected = manifest.get("templateCount")
    if expected != len(templates):
        raise SystemExit(f"manifest declares {expected} templates; loaded {len(templates)}")

    OUT_TEMPLATES.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEMPLATES.write_text(
        "/* eslint-disable */\n"
        "// Generated by scripts/generate_sources.py. Do not edit manually.\n"
        "import type { PromptWorkspaceTemplate, StarterManifest } from '../workspaces/types.js'\n\n"
        f"export const starterManifest = {dump(manifest)} as const satisfies StarterManifest\n\n"
        f"export const starterTemplates = {dump(templates)} as const satisfies Record<string, PromptWorkspaceTemplate>\n\n"
        "export const starterTemplateList = Object.values(starterTemplates) as PromptWorkspaceTemplate[]\n"
    )

    catalog = json.loads(CATALOG_PATH.read_text())
    OUT_CATALOG.write_text(
        "/* eslint-disable */\n"
        "// Generated by scripts/generate_sources.py. Do not edit manually.\n"
        f"export const webmcpCatalog = {dump(catalog)} as const\n"
        "export type WebMcpCatalogTool = (typeof webmcpCatalog.tools)[number]\n"
    )
    print(f"Generated {OUT_TEMPLATES.relative_to(ROOT)} and {OUT_CATALOG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
